"""
Tests for inferring the Maven coordinates a JAR file was built from.
"""

import zipfile
from pathlib import Path

from jgo.env import embedded_pom_entries, jar_coordinates, read_embedded_pom

# =============================================================================
# Test fixtures - build JARs on disk, since the name is part of the evidence
# =============================================================================

POM_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
{body}
</project>
"""


def pom_xml(groupId=None, artifactId=None, version=None, parent_version=None) -> str:
    """Build POM XML content, with the version optionally inherited from a parent."""
    lines = []
    if parent_version:
        lines.append(
            f"  <parent>\n"
            f"    <groupId>{groupId}</groupId>\n"
            f"    <artifactId>{artifactId}-parent</artifactId>\n"
            f"    <version>{parent_version}</version>\n"
            f"  </parent>"
        )
    if groupId:
        lines.append(f"  <groupId>{groupId}</groupId>")
    if artifactId:
        lines.append(f"  <artifactId>{artifactId}</artifactId>")
    if version:
        lines.append(f"  <version>{version}</version>")
    return POM_TEMPLATE.format(body="\n".join(lines))


def make_jar(
    tmp_path: Path,
    filename: str,
    *,
    poms: dict[tuple[str, str], str] | None = None,
    properties: dict[tuple[str, str], str] | None = None,
    manifest: str | None = None,
) -> Path:
    """
    Write a JAR containing the given Maven metadata and manifest.

    Args:
        tmp_path: Directory to write the JAR into
        filename: Name of the JAR file
        poms: (groupId, artifactId) -> pom.xml content
        properties: (groupId, artifactId) -> pom.properties content
        manifest: MANIFEST.MF content
    """
    jar_path = tmp_path / filename
    with zipfile.ZipFile(jar_path, "w") as jar:
        if manifest:
            jar.writestr("META-INF/MANIFEST.MF", manifest)
        for (groupId, artifactId), content in (poms or {}).items():
            jar.writestr(f"META-INF/maven/{groupId}/{artifactId}/pom.xml", content)
        for (groupId, artifactId), content in (properties or {}).items():
            jar.writestr(
                f"META-INF/maven/{groupId}/{artifactId}/pom.properties", content
            )
        jar.writestr("org/example/Thing.class", b"\xca\xfe\xba\xbe")
    return jar_path


def pom_properties(groupId: str, artifactId: str, version: str) -> str:
    """Build pom.properties content in the format Maven writes it."""
    return (
        "#Generated by Maven\n"
        f"groupId={groupId}\n"
        f"artifactId={artifactId}\n"
        f"version={version}\n"
    )


# =============================================================================
# Tests
# =============================================================================


class TestSingleArtifact:
    """A JAR built from exactly one Maven project."""

    def test_pom_properties(self, tmp_path):
        """pom.properties is the preferred source of the coordinate."""
        jar = make_jar(
            tmp_path,
            "ahocorasick-0.2.4.jar",
            poms={("org.ahocorasick", "ahocorasick"): pom_xml(version="0.2.4")},
            properties={
                ("org.ahocorasick", "ahocorasick"): pom_properties(
                    "org.ahocorasick", "ahocorasick", "0.2.4"
                )
            },
        )

        coordinates = jar_coordinates(jar)

        assert len(coordinates) == 1
        assert str(coordinates[0]) == "org.ahocorasick:ahocorasick:0.2.4"
        assert coordinates[0].source == "pom.properties"
        assert coordinates[0].primary

    def test_pom_xml_only(self, tmp_path):
        """Without pom.properties, the coordinate comes from the POM and its path."""
        jar = make_jar(
            tmp_path,
            "thing-1.2.3.jar",
            poms={("org.example", "thing"): pom_xml(version="1.2.3")},
        )

        coordinates = jar_coordinates(jar)

        assert str(coordinates[0]) == "org.example:thing:1.2.3"
        assert coordinates[0].source == "pom.xml"

    def test_version_inherited_from_parent(self, tmp_path):
        """A POM that omits its version inherits it from its parent."""
        jar = make_jar(
            tmp_path,
            "thing-1.2.3.jar",
            poms={("org.example", "thing"): pom_xml(parent_version="1.2.3")},
        )

        coordinates = jar_coordinates(jar)

        assert str(coordinates[0]) == "org.example:thing:1.2.3"

    def test_version_unknown(self, tmp_path):
        """A coordinate is still reported when no version can be determined."""
        jar = make_jar(
            tmp_path,
            "thing.jar",
            poms={("org.example", "thing"): pom_xml()},
        )

        coordinates = jar_coordinates(jar)

        assert str(coordinates[0]) == "org.example:thing"
        assert coordinates[0].version is None

    def test_classifier_from_filename(self, tmp_path):
        """The classifier is recoverable from the file name, but nowhere else."""
        jar = make_jar(
            tmp_path,
            "opencv-4.9.0-1.5.10-macosx-arm64.jar",
            properties={
                ("org.bytedeco", "opencv"): pom_properties(
                    "org.bytedeco", "opencv", "4.9.0-1.5.10"
                )
            },
        )

        coordinates = jar_coordinates(jar)

        assert coordinates[0].classifier == "macosx-arm64"
        assert str(coordinates[0]) == "org.bytedeco:opencv:macosx-arm64:4.9.0-1.5.10"


class TestUberJar:
    """A JAR bundling the Maven metadata of its shaded dependencies."""

    def test_primary_identified_by_filename(self, tmp_path):
        """The coordinate matching the file name is the JAR's own."""
        jar = make_jar(
            tmp_path,
            "jruby-core-9.1.17.0.jar",
            properties={
                ("com.github.jnr", "jnr-ffi"): pom_properties(
                    "com.github.jnr", "jnr-ffi", "2.1.7"
                ),
                ("org.jruby", "jruby-core"): pom_properties(
                    "org.jruby", "jruby-core", "9.1.17.0"
                ),
            },
        )

        coordinates = jar_coordinates(jar)

        assert len(coordinates) == 2
        assert str(coordinates[0]) == "org.jruby:jruby-core:9.1.17.0"
        assert coordinates[0].primary
        assert not coordinates[1].primary

    def test_primary_identified_by_manifest(self, tmp_path):
        """A file name that names no bundled artifact falls back to the manifest."""
        jar = make_jar(
            tmp_path,
            "app-standalone.jar",
            manifest=(
                "Manifest-Version: 1.0\n"
                "Implementation-Title: app\n"
                "Implementation-Vendor-Id: org.example\n"
            ),
            properties={
                ("org.example", "app"): pom_properties("org.example", "app", "3.0.0"),
                ("commons-io", "commons-io"): pom_properties(
                    "commons-io", "commons-io", "2.11.0"
                ),
            },
        )

        coordinates = jar_coordinates(jar)

        assert str(coordinates[0]) == "org.example:app:3.0.0"
        assert coordinates[0].primary

    def test_no_primary(self, tmp_path):
        """Nothing is promoted when no candidate looks like the JAR itself."""
        jar = make_jar(
            tmp_path,
            "bundle.jar",
            properties={
                ("org.example", "one"): pom_properties("org.example", "one", "1.0.0"),
                ("org.example", "two"): pom_properties("org.example", "two", "2.0.0"),
            },
        )

        coordinates = jar_coordinates(jar)

        assert len(coordinates) == 2
        assert not any(c.primary for c in coordinates)


class TestManifestFallback:
    """JARs with no embedded Maven metadata at all."""

    def test_implementation_attributes(self, tmp_path):
        """Implementation-* manifest attributes give a best-effort coordinate."""
        jar = make_jar(
            tmp_path,
            "asm-9.8.jar",
            manifest=(
                "Manifest-Version: 1.0\n"
                "Implementation-Title: asm\n"
                "Implementation-Version: 9.8\n"
                "Implementation-Vendor-Id: org.objectweb\n"
            ),
        )

        coordinates = jar_coordinates(jar)

        assert str(coordinates[0]) == "org.objectweb:asm:9.8"
        assert coordinates[0].source == "manifest"
        assert coordinates[0].primary

    def test_prose_title_falls_back_to_symbolic_name(self, tmp_path):
        """Implementation-Title is often prose, and is then not an artifactId."""
        jar = make_jar(
            tmp_path,
            "groovy-5.1.0.jar",
            manifest=(
                "Manifest-Version: 1.0\n"
                "Implementation-Title: Groovy: a powerful language\n"
                "Implementation-Vendor-Id: org.apache.groovy\n"
                "Bundle-SymbolicName: groovy\n"
                "Bundle-Version: 5.1.0\n"
            ),
        )

        coordinates = jar_coordinates(jar)

        assert str(coordinates[0]) == "org.apache.groovy:groovy:5.1.0"

    def test_symbolic_name_split(self, tmp_path):
        """With no vendor id, an OSGi symbolic name is split into groupId and artifactId."""
        jar = make_jar(
            tmp_path,
            "thing-1.0.0.jar",
            manifest=(
                "Manifest-Version: 1.0\n"
                "Bundle-SymbolicName: org.example.thing;singleton:=true\n"
                "Bundle-Version: 1.0.0\n"
            ),
        )

        coordinates = jar_coordinates(jar)

        assert str(coordinates[0]) == "org.example:thing:1.0.0"

    def test_nothing_to_go_on(self, tmp_path):
        """A JAR with no usable metadata yields no coordinates."""
        jar = make_jar(tmp_path, "mystery.jar", manifest="Manifest-Version: 1.0\n")

        assert jar_coordinates(jar) == []

    def test_not_a_jar(self, tmp_path):
        """A file that is not a zip archive yields no coordinates."""
        bogus = tmp_path / "bogus.jar"
        bogus.write_text("not a jar")

        assert jar_coordinates(bogus) == []


class TestEmbeddedPoms:
    """Reading the raw POMs out of a JAR."""

    def test_entries_and_content(self, tmp_path):
        """Only pom.xml entries are listed, and their content reads back intact."""
        content = pom_xml(groupId="org.example", artifactId="thing", version="1.0.0")
        jar = make_jar(
            tmp_path,
            "thing-1.0.0.jar",
            poms={("org.example", "thing"): content},
            properties={
                ("org.example", "thing"): pom_properties(
                    "org.example", "thing", "1.0.0"
                )
            },
        )

        entries = embedded_pom_entries(jar)

        assert entries == ["META-INF/maven/org.example/thing/pom.xml"]
        assert read_embedded_pom(jar, entries[0]) == content

    def test_sorted_entries(self, tmp_path):
        """Multiple embedded POMs are listed in a stable order."""
        jar = make_jar(
            tmp_path,
            "bundle.jar",
            poms={
                ("org.example", "two"): pom_xml(version="2.0.0"),
                ("com.example", "one"): pom_xml(version="1.0.0"),
            },
        )

        assert embedded_pom_entries(jar) == [
            "META-INF/maven/com.example/one/pom.xml",
            "META-INF/maven/org.example/two/pom.xml",
        ]

    def test_missing_entry(self, tmp_path):
        """Reading an absent entry reports nothing rather than raising."""
        jar = make_jar(tmp_path, "empty.jar")

        assert embedded_pom_entries(jar) == []
        assert read_embedded_pom(jar, "META-INF/maven/g/a/pom.xml") is None
